import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"
import { Provider } from "@/contexts/QuerryClient";
import { FilterProvider } from "@/contexts/filterContext";
import { CartProvider } from "@/contexts/cartContext";

const font = Poppins({subsets: ["latin"], weight: ['200', '300', '400', '500', '600', '700']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${font.className} w-full min-h-screen text-sm sm:text-base`}>
        <Provider>
          <FilterProvider>
            <CartProvider>
              {children}
            </CartProvider>
          </FilterProvider>
        </Provider>
      </body>
    </html>
  )
}
